name: Deploy CV

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Compile CV
      run: cd my-cv && xelatex resume

    - name: Move PDF
      run: |
        mkdir -p deploy
        mv my-cv/resume.pdf deploy/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        keep_files: false
